### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by AchalaSB** [wasmerio/go-ext-wasm#74]
Tried the example which is there in docs
```
package main

import (
    "fmt"
    wasm "github.com/wasmerio/go-ext-wasm/wasmer"
    "path"
    "runtime"
)

func simpleWasmFile() string {
    _, filename, _, _ := runtime.Caller(0)
    return path.Join(path.Dir(filename), "test", "testdata", "examples", "simple.wasm")
}

func main() {
    // Reads the WebAssembly module as bytes.
    bytes, _ := wasm.ReadBytes(simpleWasmFile())

    // Instantiates the WebAssembly module.
    instance, _ := wasm.NewInstance(bytes)

    // Close the WebAssembly instance later.
    defer instance.Close()

    // Gets the `sum` exported function from the WebAssembly instance.
    sum := instance.Exports["sum"]

    // Calls that exported function with Go standard values. The
    // WebAssembly types are inferred and values are casted
    // automatically.
    result, _ := sum(1, 2)

    fmt.Print("Result of `sum(1, 2)` is: ")
    fmt.Println(result)

}
```
error logs
```
go run main.go
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/wasmerio/go-ext-wasm/wasmer.NewInstanceWithImports.func1(0x0, 0x0, 0xc00005dd30, 0x7a47c8, 0x227f)
        /home/achala/go/src/github.com/wasmerio/go-ext-wasm/wasmer/instance.go:90 +0x1fd
github.com/wasmerio/go-ext-wasm/wasmer.newInstanceWithImports(0xc00000e060, 0xc00005de40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/achala/go/src/github.com/wasmerio/go-ext-wasm/wasmer/instance.go:161 +0x307
github.com/wasmerio/go-ext-wasm/wasmer.NewInstanceWithImports(0x0, 0x0, 0x0, 0xc00000e060, 0x0, 0x0, 0x0, 0x4f08a0, 0xc000090150, 0x4d6880)
        /home/achala/go/src/github.com/wasmerio/go-ext-wasm/wasmer/instance.go:83 +0x76
github.com/wasmerio/go-ext-wasm/wasmer.NewInstance(0x0, 0x0, 0x0, 0x0, 0x0, 0x4f08a0, 0xc000090150, 0xc000012220, 0xc00004a738)
        /home/achala/go/src/github.com/wasmerio/go-ext-wasm/wasmer/instance.go:78 +0xa1
main.main()
        /home/achala/codes/wasmexamples/main.go:20 +0x5c
exit status 2
```
Able to pass simple `.wasm` files but from github or from directory

I want to pass something like directly from github ex `https://github.com/wasmerio/go-ext-wasm/blob/master/wasmer/test/testdata/examples/simple.wasm`

how can I achieve that?

**Comment by Hywan** [comment]
Why did you close the issue :-)?

**Comment by AchalaSB** [comment]
I could able to solve this issue..

I have other issue can't able to pass f32 types? Getting results as 0. 
But in doc it is mentioned f32 is allowed.
Surprisingly f64 is working

**Comment by Hywan** [comment]
Can you open another issue please? We have test cases for `f32` and no issue have been reported yet… which doesn't we don't have bugs! Please report it :-). Thanks!
